version: '1'
services:
    development:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        ports:
            - "3000:3000"
        volumes:
            - ./src:/usr/src/app/src
            - ./public:/usr/src/app/public
            - ./package.json:/usr/src/app/package.json
        command: >
            bash -c "npm install && npm run start:dev"            